import { createHash } from 'node:crypto';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { paths } from '../config/paths';
import type { ResolvedProfile } from '../config/policy';
import type { GuestToolLimits } from '../config/schema';
import { log } from '../core/logger';
import { CHAT_HISTORY_TOOL_NAMES, FEISHU_HOST_TOOL_NAMES } from './feishu-host';

/**
 * Restricted-profile sandbox: when a run resolves to a restricted profile
 * (e.g. a guest in a DM, or anyone in a group), the bridge spawns OMP with
 * three independent layers so the run can only ever call the profile's
 * allowlisted tools:
 *
 *  1. `--tools <allowlist>` — strips built-in tools (bash/eval/write/edit/...)
 *     down to the allowlist. Host tools are registered separately and survive.
 *  2. `--config <overlay>` — disables discovery sources (so config-sourced MCP
 *     like an arbitrary-code `node_repl` never loads) and/or the shared memory
 *     backend, per the profile's `discovery` / `memory` flags.
 *  3. `--extension <hook>` — a fail-closed `tool_call` hook that hard-blocks
 *     ANY tool not in the allowlist, plus per-run call caps. This is the actual
 *     enforcement boundary; (1) and (2) just shrink the surface.
 *
 * The `full` profile never goes through any of this — it gets the full tool set.
 */

/**
 * OMP discovery sources that can contribute MCP servers / tools from external
 * tool configs (`~/.claude.json`, `~/.codex`, etc.). Disabling all of them
 * keeps a restricted run from inheriting the operator's personal MCP toolbelt.
 */
const DISCOVERY_SOURCES = [
  'native',
  'claude',
  'codex',
  'gemini',
  'github',
  'opencode',
  'cursor',
  'agents-md',
];

export interface GuestRunArgs {
  /**
   * `--tools` allowlist (built-in tool names ONLY); undefined = no
   * restriction (full built-ins). Host tools (command tools, Feishu host
   * tools) are registered over RPC and survive `--tools` filtering, and newer
   * OMP rejects unknown names in `--tools` — so they must never appear here.
   * The fail-closed hook enforces the full allowlist including host tools.
   */
  tools?: string;
  /** True when the profile pins ZERO built-ins → emit `--no-tools`. */
  noBuiltins?: boolean;
  configOverlayPaths: string[];
  extensionPaths: string[];
}

/**
 * Build the OMP config overlay for a restricted profile. Returns '' when the
 * profile keeps both discovery and memory ON (no overlay needed — OMP defaults
 * apply). Otherwise emits only the sections that must be turned off.
 */
export function profileOverlayYaml(discovery: boolean, memory: boolean): string {
  if (discovery && memory) return '';
  const lines = ['# AUTO-GENERATED by feishu-omp-bridge policy sandbox. Do not edit.'];
  if (!discovery) {
    lines.push(
      'tools:',
      '  discoveryMode: off',
      '# No external discovery: config-sourced MCP servers (e.g. an',
      '# arbitrary-code node_repl) never load for a restricted profile.',
      'disabledProviders:',
      ...DISCOVERY_SOURCES.map((s) => `  - ${s}`),
    );
  }
  if (!memory) {
    lines.push(
      '# No shared memory: blocks Memory Guidance injection AND the',
      '# retain/recall/reflect tools, so a restricted run can neither read nor',
      "# poison the operator's memory bank.",
      'memory:',
      '  backend: "off"',
    );
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Generate the fail-closed enforcement hook for a restricted profile.
 *
 * When the allowlist grants the built-in `read` tool, reads are ADDITIONALLY
 * confined to `readRoots` (the current chat's Feishu attachment cache dir):
 * the path is resolved through `realpathSync` (killing `..` and symlink
 * escapes) and must land inside one of the roots. Empty `readRoots` with
 * `read` granted blocks every read — fail closed, a restricted profile never
 * gets arbitrary-filesystem read access.
 */
export function profileHookSource(
  allowlist: string[],
  limits: GuestToolLimits,
  readRoots: string[] = [],
): string {
  const readGuard = allowlist.includes('read');
  return [
    '// AUTO-GENERATED by feishu-omp-bridge policy sandbox. Do not edit.',
    '// Fail-closed enforcement for restricted-profile runs:',
    '//  1. tool allowlist — blocks any tool not explicitly permitted;',
    '//  2. per-run call caps — blocks runaway / abusive repeat calls;',
    '//  3. read path guard — confines `read` to the chat attachment dir.',
    'import { realpathSync } from "node:fs";',
    'import { resolve as pathResolve, sep as pathSep } from "node:path";',
    `const ALLOWED = new Set(${JSON.stringify(allowlist)});`,
    `const MAX_TOTAL = ${JSON.stringify(limits.maxTotal)};`,
    `const PER_TOOL = ${JSON.stringify(limits.perTool)};`,
    `const READ_GUARD = ${JSON.stringify(readGuard)};`,
    `const READ_ROOTS = ${JSON.stringify(readRoots)};`,
    'let total = 0;',
    'const counts = Object.create(null);',
    'function readAllowed(raw) {',
    '  if (typeof raw !== "string" || raw.length === 0) return false;',
    '  // The read tool accepts `path:selector` suffixes (e.g. ":50-100");',
    '  // also try the prefix before the first ":" so selectors still work.',
    '  const candidates = [raw];',
    '  const colon = raw.indexOf(":", 1);',
    '  if (colon > 0) candidates.push(raw.slice(0, colon));',
    '  for (const candidate of candidates) {',
    '    let real;',
    '    try { real = realpathSync(pathResolve(candidate)); } catch { continue; }',
    '    for (const root of READ_ROOTS) {',
    '      let realRoot;',
    '      try { realRoot = realpathSync(root); } catch { continue; }',
    '      if (real === realRoot || real.startsWith(realRoot + pathSep)) return true;',
    '    }',
    '  }',
    '  return false;',
    '}',
    'export default function hook(pi) {',
    '  pi.on("tool_call", async (event) => {',
    '    const name = event.toolName;',
    '    if (!ALLOWED.has(name)) {',
    '      return { block: true, reason: "feishu-omp-bridge sandbox: tool \'" + name + "\' is not permitted for this sender." };',
    '    }',
    '    if (READ_GUARD && name === "read" && !readAllowed(event.input && event.input.path)) {',
    '      return { block: true, reason: "feishu-omp-bridge sandbox: read 只能访问本群聊的飞书附件,不能读取其他路径。" };',
    '    }',
    '    total += 1;',
    '    counts[name] = (counts[name] || 0) + 1;',
    '    if (MAX_TOTAL && total > MAX_TOTAL) {',
    '      return { block: true, reason: "本轮工具调用已达上限(" + MAX_TOTAL + " 次),已拒绝。请用更聚焦的一次查询。" };',
    '    }',
    '    const cap = PER_TOOL[name];',
    '    if (cap && counts[name] > cap) {',
    '      return { block: true, reason: name + " 本轮调用已达上限(" + cap + " 次),已拒绝。请合并为更少的查询。" };',
    '    }',
    '  });',
    '}',
    '',
  ].join('\n');
}

/** Signatures whose artifacts are already on disk this process. */
const cachedSignatures = new Set<string>();

/** Idempotently (re)write the overlay and/or hook for a signature's dir. */
async function ensureArtifacts(
  sig: string,
  dir: string,
  overlay: string,
  hook: string,
): Promise<{ overlayPath?: string; hookPath?: string }> {
  const overlayPath = join(dir, 'overlay.yml');
  const hookPath = join(dir, 'allowlist-hook.mjs');
  if (!cachedSignatures.has(sig)) {
    await mkdir(dir, { recursive: true });
    if (overlay) await writeIfChanged(overlayPath, overlay);
    if (hook) await writeIfChanged(hookPath, hook);
    cachedSignatures.add(sig);
    log.info('policy', 'artifacts-ready', { sig });
  }
  return {
    overlayPath: overlay ? overlayPath : undefined,
    hookPath: hook ? hookPath : undefined,
  };
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  const existing = await readFile(path, 'utf8').catch(() => undefined);
  if (existing === content) return;
  await writeFile(path, content, 'utf8');
}

/**
 * Resolve the per-run OMP args for a profile. The `--tools` allowlist + the
 * fail-closed hook are emitted ONLY for a restricted profile (built-ins pinned);
 * the config overlay (discovery / memory off) is emitted whenever the profile
 * disables either, even for a `full` profile — so those knobs are never silently
 * ignored. A plain `full` profile (full built-ins, discovery + memory on)
 * returns no run args at all. Artifacts are generated on demand under a
 * per-profile directory keyed by a content signature, so concurrently-active
 * profiles don't clobber each other.
 *
 * The hook allowlist = the profile's built-in tools + its command-tool names +
 * the Feishu host tool names when `feishuHostTools` is on (otherwise the hook
 * would block the very host tools the caller just registered). When the
 * profile grants `read`, pass `readRoots` (the current chat's media dir) —
 * omitting it blocks every read for that run (fail closed).
 *
 * Note: the profile system prompt is NOT injected here — it's prepended to the
 * user prompt by the caller. `--append-system-prompt` was found to hang the
 * codex (gpt-5.5) request intermittently.
 */
export async function buildProfileRunArgs(
  profile: ResolvedProfile,
  opts: { readRoots?: string[] } = {},
): Promise<GuestRunArgs> {
  const restricted = profile.restricted;
  const allowlist = restricted
    ? [
        ...new Set([
          ...profile.builtinTools,
          ...profile.commandTools.map((t) => t.name),
          ...(profile.feishuHostTools ? FEISHU_HOST_TOOL_NAMES : []),
          ...(profile.historyTools ? CHAT_HISTORY_TOOL_NAMES : []),
        ]),
      ]
    : [];
  const overlay = profileOverlayYaml(profile.discovery, profile.memory);
  let hook = '';
  if (restricted) {
    const perTool: Record<string, number> = {};
    if (profile.historyTools) {
      // Hard per-run caps for the history surface: enough to find and pull a
      // few files, not enough to trawl the chat.
      perTool.feishu_list_recent = 3;
      perTool.feishu_fetch_attachment = 5;
    }
    for (const t of profile.commandTools) {
      if (typeof t.maxCalls === 'number') perTool[t.name] = t.maxCalls;
    }
    const limits: GuestToolLimits = { maxTotal: profile.maxToolCalls, perTool };
    hook = profileHookSource(allowlist, limits, opts.readRoots ?? []);
  }
  // Operator-supplied extension hooks (your own tool / rate-call limiter .mjs),
  // composable with the auto hook. Warn on a missing path but pass it through:
  // a vanished limiter must fail the run loudly, never silently disappear.
  const custom = profile.extensions;
  for (const p of custom) {
    if (!(await fileExists(p))) log.warn('policy', 'extension-missing', { path: p });
  }
  let overlayPath: string | undefined;
  let hookPath: string | undefined;
  if (overlay || hook) {
    const sig = createHash('sha1')
      .update(JSON.stringify({ allowlist, overlay, hook }))
      .digest('hex')
      .slice(0, 12);
    ({ overlayPath, hookPath } = await ensureArtifacts(sig, join(paths.guestDir, sig), overlay, hook));
  }
  return {
    tools: restricted && profile.builtinTools.length > 0 ? [...new Set(profile.builtinTools)].join(',') : undefined,
    noBuiltins: restricted && profile.builtinTools.length === 0,
    configOverlayPaths: overlayPath ? [overlayPath] : [],
    extensionPaths: [...(hookPath ? [hookPath] : []), ...custom],
  };
}

async function fileExists(p: string): Promise<boolean> {
  return access(p).then(() => true).catch(() => false);
}
