import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { paths } from '../config/paths';
import {
  getGuestToolAllowlist,
  getGuestToolLimits,
  type AppConfig,
  type GuestToolLimits,
} from '../config/schema';
import { log } from '../core/logger';

/**
 * Guest sandbox: when a non-trusted sender triggers a run, the bridge spawns
 * OMP with three independent layers so a stranger can only ever call the
 * whitelisted host tools:
 *
 *  1. `--tools <allowlist>` — strips built-in tools (bash/eval/write/edit/...)
 *     down to the allowlist. Host tools are registered separately and survive.
 *  2. `--config <overlay>` — disables every discovery source so config-sourced
 *     MCP servers (e.g. an arbitrary-code `node_repl`) never load. Cleanup so
 *     the model isn't even shown them.
 *  3. `--extension <hook>` — a fail-closed `tool_call` hook that hard-blocks
 *     ANY tool whose name is not in the allowlist. This is the actual
 *     enforcement boundary; (1) and (2) just shrink the surface. The hook
 *     catches anything (1)/(2) miss (bundled MCP, generate_image, future leaks).
 *
 * Trusted senders never go through any of this — they get the full tool set.
 */

/**
 * OMP discovery sources that can contribute MCP servers / tools from external
 * tool configs (`~/.claude.json`, `~/.codex`, etc.). Disabling all of them
 * keeps a guest run from inheriting the operator's personal MCP toolbelt.
 */
const DISCOVERY_SOURCES = [
  'native',
  'claude',
  'codex',
  'gemini',
  'github',
  'opencode',
  'cursor',
  'agents-md',
];

/**
 * `--tools` value forcing ZERO built-ins. OMP treats an unknown tool name as
 * "allow nothing matching" rather than an error, and an empty `--tools` is
 * dropped (reverting to full defaults), so we need a non-empty sentinel.
 */
const NO_BUILTINS_SENTINEL = '__bridge_no_builtins__';

const overlayPath = join(paths.guestDir, 'overlay.yml');
const hookPath = join(paths.guestDir, 'allowlist-hook.mjs');

export function guestOverlayYaml(): string {
  return [
    '# AUTO-GENERATED by feishu-omp-bridge guest sandbox. Do not edit.',
    'tools:',
    '  discoveryMode: off',
    '# No shared memory for guests: blocks Memory Guidance injection AND the',
    '# retain/recall/reflect tools, so a stranger can neither read nor poison',
    '# the operator\'s memory bank.',
    'memory:',
    '  backend: "off"',
    'disabledProviders:',
    ...DISCOVERY_SOURCES.map((s) => `  - ${s}`),
    '',
  ].join('\n');
}

export function guestHookSource(allowlist: string[], limits: GuestToolLimits): string {
  return [
    '// AUTO-GENERATED by feishu-omp-bridge guest sandbox. Do not edit.',
    '// Fail-closed enforcement for sandboxed (non-trusted) senders:',
    '//  1. tool allowlist — blocks any tool not explicitly permitted;',
    '//  2. per-run call caps — blocks runaway / abusive repeat calls.',
    `const ALLOWED = new Set(${JSON.stringify(allowlist)});`,
    `const MAX_TOTAL = ${JSON.stringify(limits.maxTotal)};`,
    `const PER_TOOL = ${JSON.stringify(limits.perTool)};`,
    'let total = 0;',
    'const counts = Object.create(null);',
    'export default function hook(pi) {',
    '  pi.on("tool_call", async (event) => {',
    '    const name = event.toolName;',
    '    if (!ALLOWED.has(name)) {',
    '      return { block: true, reason: "feishu-omp-bridge guest sandbox: tool \'" + name + "\' is not permitted for this sender." };',
    '    }',
    '    total += 1;',
    '    counts[name] = (counts[name] || 0) + 1;',
    '    if (MAX_TOTAL && total > MAX_TOTAL) {',
    '      return { block: true, reason: "本轮工具调用已达上限(" + MAX_TOTAL + " 次),已拒绝。请用更聚焦的一次查询。" };',
    '    }',
    '    const cap = PER_TOOL[name];',
    '    if (cap && counts[name] > cap) {',
    '      return { block: true, reason: name + " 本轮调用已达上限(" + cap + " 次),已拒绝。请合并为更少的查询。" };',
    '    }',
    '  });',
    '}',
    '',
  ].join('\n');
}

let cachedSignature: string | undefined;

/** Idempotently (re)write the overlay + hook files. Cached by allowlist + limits. */
async function ensureArtifacts(allowlist: string[], limits: GuestToolLimits): Promise<void> {
  const signature = JSON.stringify({ allowlist, limits });
  if (cachedSignature !== signature) {
    await mkdir(paths.guestDir, { recursive: true });
    await writeIfChanged(overlayPath, guestOverlayYaml());
    await writeIfChanged(hookPath, guestHookSource(allowlist, limits));
    cachedSignature = signature;
    log.info('guest', 'artifacts-ready', { allowlist, limits });
  }
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  const existing = await readFile(path, 'utf8').catch(() => undefined);
  if (existing === content) return;
  await writeFile(path, content, 'utf8');
}

export interface GuestRunArgs {
  tools: string;
  configOverlayPaths: string[];
  extensionPaths: string[];
}

/**
 * Resolve the per-run OMP args that sandbox a guest sender. Generates the
 * overlay + hook artifacts on demand. The returned `tools` strips built-ins to
 * the allowlist (or zero, via sentinel, when the allowlist has no built-ins).
 *
 * Note: the guest system prompt is NOT injected here — it's prepended to the
 * user prompt in channel.ts. `--append-system-prompt` was found to hang the
 * codex (gpt-5.5) request intermittently.
 */
export async function buildGuestRunArgs(cfg: AppConfig): Promise<GuestRunArgs> {
  const allowlist = getGuestToolAllowlist(cfg);
  await ensureArtifacts(allowlist, getGuestToolLimits(cfg));
  return {
    tools: allowlist.length > 0 ? allowlist.join(',') : NO_BUILTINS_SENTINEL,
    configOverlayPaths: [overlayPath],
    extensionPaths: [hookPath],
  };
}
