import { access, chmod, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, extname } from 'node:path';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { paths } from './paths';
import type { AppConfig, TenantBrand } from './schema';
import { secretKeyForApp } from './schema';

/**
 * Resolve which config file to read/write. An explicit non-default path
 * (`--config foo.yaml`, a test tmp file) is honored verbatim. Otherwise we pick
 * the first existing of config.json / config.yaml / config.yml, falling back to
 * config.json (the default for a first write). This lets a hand-written YAML
 * config be discovered — and rewritten in place — without every caller knowing
 * the format; callers keep passing `paths.configFile` (or nothing).
 */
export async function resolveConfigPath(explicit?: string): Promise<string> {
  if (explicit && explicit !== paths.configFile) return explicit;
  for (const p of [paths.configFile, paths.configFileYaml, paths.configFileYml]) {
    try {
      await access(p);
      return p;
    } catch {
      // not present — try the next candidate
    }
  }
  return paths.configFile;
}

function isYamlPath(path: string): boolean {
  const ext = extname(path).toLowerCase();
  return ext === '.yaml' || ext === '.yml';
}

export async function loadConfig(path?: string): Promise<Partial<AppConfig>> {
  const resolved = await resolveConfigPath(path);
  try {
    const text = await readFile(resolved, 'utf8');
    const parsed = isYamlPath(resolved)
      ? (parseYaml(text) as Partial<AppConfig> | null | undefined)
      : (JSON.parse(text) as Partial<AppConfig>);
    return parsed ?? {};
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw err;
  }
}

/**
 * Atomic write: write to a sibling temp file with 0600 perms, then rename
 * (atomic on POSIX) into place. Avoids the partial-write window where a
 * crash could leave the config truncated, and keeps secret-bearing bytes
 * from ever existing at the final path with looser perms.
 */
/**
 * Build an AppConfig that points the app's secret at the encrypted local
 * keystore via an exec-provider SecretRef. Used by /account change and the
 * first-run migration path. `prior` (the existing config) is spread through so
 * non-credential top-level sections — `preferences`, `relay`, future `mcp`, … —
 * survive the rewrite; only `accounts` and `secrets` are rebuilt below.
 *
 * The provider command is a thin shell wrapper bridge writes under
 * `~/.feishu-omp-bridge/secrets-getter` (always user-owned, never a symlink) so
 * lark-cli's AssertSecurePath audit accepts it regardless of how node was
 * installed (Homebrew / Volta / system pkg may put node behind a symlink
 * or root-own it). The wrapper internally `exec`s the real node + bridge
 * with `secrets get`. Bridge itself short-circuits the spawn and reads the
 * keystore directly when it sees its own wrapper path in `command`.
 */
export async function buildEncryptedAccountConfig(
  appId: string,
  tenant: TenantBrand,
  prior?: Partial<AppConfig>,
): Promise<AppConfig> {
  const wrapperPath = await ensureSecretsGetterWrapper();
  return {
    // Carry over every other top-level section verbatim; accounts + secrets
    // are rebuilt below to point at the encrypted keystore (any plaintext
    // secret or stale provider in `prior` is overwritten, not preserved).
    ...prior,
    accounts: {
      app: {
        id: appId,
        secret: {
          source: 'exec',
          provider: 'bridge',
          id: secretKeyForApp(appId),
        },
        tenant,
      },
    },
    secrets: {
      providers: {
        bridge: {
          source: 'exec',
          command: wrapperPath,
          // The wrapper has args baked in; pass none here.
          args: [],
        },
      },
    },
  };
}

/**
 * Write (or rewrite) the secrets-getter wrapper to point at the currently-
 * running node + bridge entry script. Always rewrites — node path can move
 * between bridge runs (nvm version switch, re-install) and the wrapper
 * must stay in sync. Returns the wrapper path.
 *
 * File perms 0700 so audit's `world/group-writable` check passes (and
 * extra restrictive — wrapper is a private user resource).
 */
export async function ensureSecretsGetterWrapper(): Promise<string> {
  const wrapperPath = paths.secretsGetterScript;
  const node = process.execPath;
  const bridgeEntry = process.argv[1] ?? '';
  // Single-quoted shell-safe strings: escape any embedded single quotes.
  const sq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
  const content =
    `#!/bin/sh\n` +
    `# Auto-generated by feishu-omp-bridge. Do not edit.\n` +
    `# Forwards exec-provider requests to: node bridge secrets get\n` +
    `exec ${sq(node)} ${sq(bridgeEntry)} secrets get "$@"\n`;

  await mkdir(dirname(wrapperPath), { recursive: true });
  const tmp = `${wrapperPath}.tmp-${process.pid}`;
  await writeFile(tmp, content, 'utf8');
  await chmod(tmp, 0o700);
  await rename(tmp, wrapperPath);
  return wrapperPath;
}

export async function saveConfig(cfg: AppConfig, path?: string): Promise<void> {
  const resolved = await resolveConfigPath(path);
  await mkdir(dirname(resolved), { recursive: true });
  const tmp = `${resolved}.tmp-${process.pid}`;
  // Write in the resolved file's format. YAML round-trips drop hand-written
  // comments — programmatic edits (/config) reserialize the doc.
  const text = isYamlPath(resolved) ? stringifyYaml(cfg) : `${JSON.stringify(cfg, null, 2)}\n`;
  await writeFile(tmp, text, 'utf8');
  // chmod the temp file before rename, so the destination path is never
  // visible with default permissions.
  await chmod(tmp, 0o600);
  await rename(tmp, resolved);
}
